name: Call MQTT for Opening of PR
on:
  pull_request:
    types: [closed]

jobs:
  send-message-to-mqtt:
    name: Publish Opening of PR to mqtt broker
    runs-on: ubuntu-latest
    steps:
      - uses: juhrlass/mqtt-action@master
        with:
          protocol: mqtt
          host: io.adafruit.com
          port: 1883
          topic: "mayankOnAdafruit/feeds/pr-close"
          message: "true"
          username: "mayankOnAdafruit"
          password: ${{ secrets.MQTT_BROKER_PASSWORD }}
